-- Active: 1696422135849@@127.0.0.1@3306@world
SHOW DATABASES;
CREATE DATABASE FEES_CLEARANCE;
CREATE TABLE STUDENTS(STUDENTID VARCHAR() PRIMARY KEY NOT NULL, FNAME VARCHAR() NOT NULL, LNAME VARCHAR() NOT NULL,CLASS VARCHAR() NOT NULL, RESIDENCE VARCHAR()NOT NULL, PAY_CODE VARCHAR() NOT NULL, ACADEMIC_LEVEL VARCHAR() NOT NULL, SPECIFICATION VARCHAR() NOT NULL, );
CREATE TABLE CLASS(PAY_CODE VARCHAR() PRIMARY KEY NOT NULL, CLASS VARCHAR() NOT NULL, STRUCTURED_FEES VARCHAR() NOT NULL);
USE MATHDB;
CREATE TABLE PAYMENT(PAYMENTID VARCHAR() PRIMARY KEY NOT NULL, STUDENTID VARCHAR() NOT NULL, FEES_TYPE VARCHAR()NOT NULL, AMOUNT_PAID VARCHAR() NOT NULL, BALANCE VARCHAR() NOT NULL)